services:
  web:
    build: ./web
    volumes:
      - app:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "${FRONT_HTTP_PORT_NO:-80}:80"
      - "${FRONT_HTTPS_PORT_NO:-443}:443"
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    environment:
      DOMAINS: "${WEB_DOMAIN} -> http://web:80 ${ADD_DOMAIN}"
      STAGE: "${HTTPS_PORTAL_STAGE}"
      CLIENT_MAX_BODY_SIZE: 20M
      FORCE_RENEW: "${HTTPS_PORTAL_FORCE_RENEW}"
    depends_on:
      - web

  app:
    image: wordpress:php${DOCKER_IMAGE_WORDPRESS_PHP_VERSION}-fpm-alpine
    depends_on:
      - db
    volumes:
      - app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    env_file: .db.env

  db:
    image: mariadb:lts
    volumes:
      - db-data:/var/lib/mysql
    env_file: .db.env

volumes:
  app:
  db-data:
  https-portal-data:
